name: Generate Helm Docs
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: AaronSeibert/charts-seibert-family
          path: helm-docs
          ref: main
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install Helm Docs
        run: go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest
      - name: Retrieve Generated Files
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - name: Update Chart.yaml
        run: cat artifacts/Chart.yaml > Chart.yaml
      - name: Generate README.md
        run: $HOME/go/bin/helm-docs -t ./helm-docs/templates/common.gotmpl -t ./helm-docs/templates/chart.gotmpl
      - name: Upload readme for other flows 
        uses: actions/upload-artifact@v4
        with:
          name: readme
          path: README.md
